# Generated by Django 4.1.2 on 2022-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_notification_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ratingfield',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Resume', 'Resume'), ('Coursera Certificates', 'Coursera Certificates')], default='profile', max_length=30),
        ),
    ]
