# Generated by Django 4.1.2 on 2022-11-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_feedback_ratingfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comments',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ratingfield',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Resume', 'Resume'), ('Coursera Certificates', 'Coursera Certificates'), ('Profile', 'Profile')], default='profile', max_length=30),
        ),
    ]
